EXTENSION_TO_FOLDER = {
    'jpg': 'Images',
    'jpeg': 'Images',
    'png': 'Images',
    'gif': 'Images',
    'txt': 'TextFiles',
    'pdf': 'PDFs',
    'doc': 'Documents',
    'docx': 'Documents',
    'bat': 'Scripts',
    'exe': 'Installation_files',
    'mp4': 'Videos',
    'mkv': 'Videos',
    'mp3': 'Music',
    'opus': 'Music',
}
